
package motion.database.ws.authorizationWCF;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "AuthorizationException", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AuthorizationService")
public class IAuthorizationWSAlterSessionVisibilityAuthorizationExceptionFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AuthorizationException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IAuthorizationWSAlterSessionVisibilityAuthorizationExceptionFaultFaultMessage(String message, AuthorizationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IAuthorizationWSAlterSessionVisibilityAuthorizationExceptionFaultFaultMessage(String message, AuthorizationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: motion.database.ws.authorizationWCF.AuthorizationException
     */
    public AuthorizationException getFaultInfo() {
        return faultInfo;
    }

}
