
package motion.database.ws.basicUpdateService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "BasicUpdatesService", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", wsdlLocation = "http://dbpawell/Motion/BasicUpdatesService.asmx?WSDL")
public class BasicUpdatesService
    extends Service
{

    private final static URL BASICUPDATESSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://dbpawell/Motion/BasicUpdatesService.asmx?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BASICUPDATESSERVICE_WSDL_LOCATION = url;
    }

    public BasicUpdatesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicUpdatesService() {
        super(BASICUPDATESSERVICE_WSDL_LOCATION, new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", "BasicUpdatesService"));
    }

    /**
     * 
     * @return
     *     returns BasicUpdatesServiceSoap
     */
    @WebEndpoint(name = "BasicUpdatesServiceSoap")
    public BasicUpdatesServiceSoap getBasicUpdatesServiceSoap() {
        return (BasicUpdatesServiceSoap)super.getPort(new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", "BasicUpdatesServiceSoap"), BasicUpdatesServiceSoap.class);
    }

}
