
package motion.database.ws.UserPersonalSpaceWCF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IUserPersonalSpaceWS", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserPersonalSpaceWS {


    /**
     * 
     * @param basketName
     * @throws IUserPersonalSpaceWSCreateBasketUPSExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateBasket", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService/IUserPersonalSpaceWS/CreateBasket")
    @RequestWrapper(localName = "CreateBasket", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.CreateBasket")
    @ResponseWrapper(localName = "CreateBasketResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.CreateBasketResponse")
    public void createBasket(
        @WebParam(name = "basketName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        String basketName)
        throws IUserPersonalSpaceWSCreateBasketUPSExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param basketName
     * @throws IUserPersonalSpaceWSRemoveBasketUPSExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveBasket", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService/IUserPersonalSpaceWS/RemoveBasket")
    @RequestWrapper(localName = "RemoveBasket", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.RemoveBasket")
    @ResponseWrapper(localName = "RemoveBasketResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.RemoveBasketResponse")
    public void removeBasket(
        @WebParam(name = "basketName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        String basketName)
        throws IUserPersonalSpaceWSRemoveBasketUPSExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param resourceID
     * @param basketName
     * @param entity
     * @throws IUserPersonalSpaceWSAddEntityToBasketUPSExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "AddEntityToBasket", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService/IUserPersonalSpaceWS/AddEntityToBasket")
    @RequestWrapper(localName = "AddEntityToBasket", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.AddEntityToBasket")
    @ResponseWrapper(localName = "AddEntityToBasketResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.AddEntityToBasketResponse")
    public void addEntityToBasket(
        @WebParam(name = "basketName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        String basketName,
        @WebParam(name = "resourceID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        int resourceID,
        @WebParam(name = "entity", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        String entity)
        throws IUserPersonalSpaceWSAddEntityToBasketUPSExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param resourceID
     * @param basketName
     * @param entity
     * @throws IUserPersonalSpaceWSRemoveEntityFromBasketUPSExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveEntityFromBasket", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService/IUserPersonalSpaceWS/RemoveEntityFromBasket")
    @RequestWrapper(localName = "RemoveEntityFromBasket", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.RemoveEntityFromBasket")
    @ResponseWrapper(localName = "RemoveEntityFromBasketResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.RemoveEntityFromBasketResponse")
    public void removeEntityFromBasket(
        @WebParam(name = "basketName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        String basketName,
        @WebParam(name = "resourceID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        int resourceID,
        @WebParam(name = "entity", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        String entity)
        throws IUserPersonalSpaceWSRemoveEntityFromBasketUPSExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param basketName
     * @return
     *     returns motion.database.ws.UserPersonalSpaceWCF.ListBasketPerformersWithAttributesXMLResponse.ListBasketPerformersWithAttributesXMLResult
     * @throws IUserPersonalSpaceWSListBasketPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListBasketPerformersWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService/IUserPersonalSpaceWS/ListBasketPerformersWithAttributesXML")
    @WebResult(name = "ListBasketPerformersWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
    @RequestWrapper(localName = "ListBasketPerformersWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.ListBasketPerformersWithAttributesXML")
    @ResponseWrapper(localName = "ListBasketPerformersWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.ListBasketPerformersWithAttributesXMLResponse")
    public motion.database.ws.UserPersonalSpaceWCF.ListBasketPerformersWithAttributesXMLResponse.ListBasketPerformersWithAttributesXMLResult listBasketPerformersWithAttributesXML(
        @WebParam(name = "basketName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        String basketName)
        throws IUserPersonalSpaceWSListBasketPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param basketName
     * @return
     *     returns motion.database.ws.UserPersonalSpaceWCF.ListBasketSessionsWithAttributesXMLResponse.ListBasketSessionsWithAttributesXMLResult
     * @throws IUserPersonalSpaceWSListBasketSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListBasketSessionsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService/IUserPersonalSpaceWS/ListBasketSessionsWithAttributesXML")
    @WebResult(name = "ListBasketSessionsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
    @RequestWrapper(localName = "ListBasketSessionsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.ListBasketSessionsWithAttributesXML")
    @ResponseWrapper(localName = "ListBasketSessionsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.ListBasketSessionsWithAttributesXMLResponse")
    public motion.database.ws.UserPersonalSpaceWCF.ListBasketSessionsWithAttributesXMLResponse.ListBasketSessionsWithAttributesXMLResult listBasketSessionsWithAttributesXML(
        @WebParam(name = "basketName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        String basketName)
        throws IUserPersonalSpaceWSListBasketSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param basketName
     * @return
     *     returns motion.database.ws.UserPersonalSpaceWCF.ListBasketTrialsWithAttributesXMLResponse.ListBasketTrialsWithAttributesXMLResult
     * @throws IUserPersonalSpaceWSListBasketTrialsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListBasketTrialsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService/IUserPersonalSpaceWS/ListBasketTrialsWithAttributesXML")
    @WebResult(name = "ListBasketTrialsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
    @RequestWrapper(localName = "ListBasketTrialsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.ListBasketTrialsWithAttributesXML")
    @ResponseWrapper(localName = "ListBasketTrialsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.ListBasketTrialsWithAttributesXMLResponse")
    public motion.database.ws.UserPersonalSpaceWCF.ListBasketTrialsWithAttributesXMLResponse.ListBasketTrialsWithAttributesXMLResult listBasketTrialsWithAttributesXML(
        @WebParam(name = "basketName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        String basketName)
        throws IUserPersonalSpaceWSListBasketTrialsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param basketName
     * @return
     *     returns motion.database.ws.UserPersonalSpaceWCF.ListBasketSegmentsWithAttributesXMLResponse.ListBasketSegmentsWithAttributesXMLResult
     * @throws IUserPersonalSpaceWSListBasketSegmentsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListBasketSegmentsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService/IUserPersonalSpaceWS/ListBasketSegmentsWithAttributesXML")
    @WebResult(name = "ListBasketSegmentsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
    @RequestWrapper(localName = "ListBasketSegmentsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.ListBasketSegmentsWithAttributesXML")
    @ResponseWrapper(localName = "ListBasketSegmentsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", className = "motion.database.ws.UserPersonalSpaceWCF.ListBasketSegmentsWithAttributesXMLResponse")
    public motion.database.ws.UserPersonalSpaceWCF.ListBasketSegmentsWithAttributesXMLResponse.ListBasketSegmentsWithAttributesXMLResult listBasketSegmentsWithAttributesXML(
        @WebParam(name = "basketName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService")
        String basketName)
        throws IUserPersonalSpaceWSListBasketSegmentsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

}
