
package motion.database.ws.userPersonalSpaceWCF;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UserPersonalSpace", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", wsdlLocation = "http://dbpawell.pjwstk.edu.pl/Motion/res/UserPersonalSpaceWSStandalone.wsdl")
public class UserPersonalSpace
    extends Service
{

    private final static URL USERPERSONALSPACE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(motion.database.ws.userPersonalSpaceWCF.UserPersonalSpace.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = motion.database.ws.userPersonalSpaceWCF.UserPersonalSpace.class.getResource(".");
            url = new URL(baseUrl, "http://dbpawell.pjwstk.edu.pl/Motion/res/UserPersonalSpaceWSStandalone.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://dbpawell.pjwstk.edu.pl/Motion/res/UserPersonalSpaceWSStandalone.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERPERSONALSPACE_WSDL_LOCATION = url;
    }

    public UserPersonalSpace(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserPersonalSpace() {
        super(USERPERSONALSPACE_WSDL_LOCATION, new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", "UserPersonalSpace"));
    }

    /**
     * 
     * @return
     *     returns IUserPersonalSpaceWS
     */
    @WebEndpoint(name = "BasicHttpBinding_IUserPersonalSpaceWS")
    public IUserPersonalSpaceWS getBasicHttpBindingIUserPersonalSpaceWS() {
        return super.getPort(new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", "BasicHttpBinding_IUserPersonalSpaceWS"), IUserPersonalSpaceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUserPersonalSpaceWS
     */
    @WebEndpoint(name = "BasicHttpBinding_IUserPersonalSpaceWS")
    public IUserPersonalSpaceWS getBasicHttpBindingIUserPersonalSpaceWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/UserPersonalSpaceService", "BasicHttpBinding_IUserPersonalSpaceWS"), IUserPersonalSpaceWS.class, features);
    }

}
