
package motion.database.ws.administrationWCF;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AdministrationWS", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", wsdlLocation = "http://83.230.112.43/Motion/AdministrationWS.svc?wsdl")
public class AdministrationWS
    extends Service
{

    private final static URL ADMINISTRATIONWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(motion.database.ws.administrationWCF.AdministrationWS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = motion.database.ws.administrationWCF.AdministrationWS.class.getResource(".");
            url = new URL(baseUrl, "http://83.230.112.43/Motion/AdministrationWS.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://83.230.112.43/Motion/AdministrationWS.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ADMINISTRATIONWS_WSDL_LOCATION = url;
    }

    public AdministrationWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdministrationWS() {
        super(ADMINISTRATIONWS_WSDL_LOCATION, new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", "AdministrationWS"));
    }

    /**
     * 
     * @return
     *     returns IAdministrationWS
     */
    @WebEndpoint(name = "BasicHttpBinding_IAdministrationWS")
    public IAdministrationWS getBasicHttpBindingIAdministrationWS() {
        return super.getPort(new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", "BasicHttpBinding_IAdministrationWS"), IAdministrationWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAdministrationWS
     */
    @WebEndpoint(name = "BasicHttpBinding_IAdministrationWS")
    public IAdministrationWS getBasicHttpBindingIAdministrationWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", "BasicHttpBinding_IAdministrationWS"), IAdministrationWS.class, features);
    }

}
