
package motion.database.ws.administrationWCF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IAdministrationWS", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAdministrationWS {


    /**
     * 
     * @param groupName
     * @param entity
     * @throws IAdministrationWSDefineAttriubeGroupAdministrationOperationExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "DefineAttriubeGroup", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService/IAdministrationWS/DefineAttriubeGroup")
    @RequestWrapper(localName = "DefineAttriubeGroup", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.DefineAttriubeGroup")
    @ResponseWrapper(localName = "DefineAttriubeGroupResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.DefineAttriubeGroupResponse")
    public void defineAttriubeGroup(
        @WebParam(name = "groupName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String groupName,
        @WebParam(name = "entity", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String entity)
        throws IAdministrationWSDefineAttriubeGroupAdministrationOperationExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param groupName
     * @param entity
     * @throws IAdministrationWSRemoveAttributeGroupAdministrationOperationExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveAttributeGroup", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService/IAdministrationWS/RemoveAttributeGroup")
    @RequestWrapper(localName = "RemoveAttributeGroup", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.RemoveAttributeGroup")
    @ResponseWrapper(localName = "RemoveAttributeGroupResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.RemoveAttributeGroupResponse")
    public void removeAttributeGroup(
        @WebParam(name = "groupName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String groupName,
        @WebParam(name = "entity", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String entity)
        throws IAdministrationWSRemoveAttributeGroupAdministrationOperationExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param attributeName
     * @param unit
     * @param groupName
     * @param pluginDescriptor
     * @param storageType
     * @param entity
     * @param isEnum
     * @param dataSubtype
     * @throws IAdministrationWSDefineAttributeAdministrationOperationExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "DefineAttribute", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService/IAdministrationWS/DefineAttribute")
    @RequestWrapper(localName = "DefineAttribute", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.DefineAttribute")
    @ResponseWrapper(localName = "DefineAttributeResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.DefineAttributeResponse")
    public void defineAttribute(
        @WebParam(name = "attributeName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String attributeName,
        @WebParam(name = "groupName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String groupName,
        @WebParam(name = "entity", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String entity,
        @WebParam(name = "storageType", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String storageType,
        @WebParam(name = "isEnum", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        boolean isEnum,
        @WebParam(name = "pluginDescriptor", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String pluginDescriptor,
        @WebParam(name = "dataSubtype", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String dataSubtype,
        @WebParam(name = "unit", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String unit)
        throws IAdministrationWSDefineAttributeAdministrationOperationExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param attributeName
     * @param groupName
     * @param entity
     * @throws IAdministrationWSRemoveAttributeAdministrationOperationExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveAttribute", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService/IAdministrationWS/RemoveAttribute")
    @RequestWrapper(localName = "RemoveAttribute", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.RemoveAttribute")
    @ResponseWrapper(localName = "RemoveAttributeResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.RemoveAttributeResponse")
    public void removeAttribute(
        @WebParam(name = "attributeName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String attributeName,
        @WebParam(name = "groupName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String groupName,
        @WebParam(name = "entity", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String entity)
        throws IAdministrationWSRemoveAttributeAdministrationOperationExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param attributeName
     * @param groupName
     * @param clearExisting
     * @param entity
     * @param value
     * @throws IAdministrationWSAddAttributeEnumValueAdministrationOperationExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "AddAttributeEnumValue", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService/IAdministrationWS/AddAttributeEnumValue")
    @RequestWrapper(localName = "AddAttributeEnumValue", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.AddAttributeEnumValue")
    @ResponseWrapper(localName = "AddAttributeEnumValueResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.AddAttributeEnumValueResponse")
    public void addAttributeEnumValue(
        @WebParam(name = "attributeName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String attributeName,
        @WebParam(name = "groupName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String groupName,
        @WebParam(name = "entity", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String entity,
        @WebParam(name = "value", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        String value,
        @WebParam(name = "clearExisting", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        boolean clearExisting)
        throws IAdministrationWSAddAttributeEnumValueAdministrationOperationExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param olderThanMinutes
     * @throws IAdministrationWSDownloadAreaCleanupAdministrationOperationExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "DownloadAreaCleanup", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService/IAdministrationWS/DownloadAreaCleanup")
    @RequestWrapper(localName = "DownloadAreaCleanup", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.DownloadAreaCleanup")
    @ResponseWrapper(localName = "DownloadAreaCleanupResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService", className = "motion.database.ws.administrationWCF.DownloadAreaCleanupResponse")
    public void downloadAreaCleanup(
        @WebParam(name = "olderThanMinutes", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/AdministrationService")
        int olderThanMinutes)
        throws IAdministrationWSDownloadAreaCleanupAdministrationOperationExceptionFaultFaultMessage
    ;

}
