
package motion.database.ws.basicQueriesServiceWCF;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BasicQueriesWS", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", wsdlLocation = "http://v21.pjwstk.edu.pl/Motion/res/BasicQueriesWSStandalone.wsdl")
public class BasicQueriesWS
    extends Service
{

    private final static URL BASICQUERIESWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(motion.database.ws.basicQueriesServiceWCF.BasicQueriesWS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = motion.database.ws.basicQueriesServiceWCF.BasicQueriesWS.class.getResource(".");
            url = new URL(baseUrl, "http://v21.pjwstk.edu.pl/Motion/res/BasicQueriesWSStandalone.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://v21.pjwstk.edu.pl/Motion/res/BasicQueriesWSStandalone.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BASICQUERIESWS_WSDL_LOCATION = url;
    }

    public BasicQueriesWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicQueriesWS() {
        super(BASICQUERIESWS_WSDL_LOCATION, new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", "BasicQueriesWS"));
    }

    /**
     * 
     * @return
     *     returns IBasicQueriesWS
     */
    @WebEndpoint(name = "BasicHttpBinding_IBasicQueriesWS")
    public IBasicQueriesWS getBasicHttpBindingIBasicQueriesWS() {
        return super.getPort(new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", "BasicHttpBinding_IBasicQueriesWS"), IBasicQueriesWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBasicQueriesWS
     */
    @WebEndpoint(name = "BasicHttpBinding_IBasicQueriesWS")
    public IBasicQueriesWS getBasicHttpBindingIBasicQueriesWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", "BasicHttpBinding_IBasicQueriesWS"), IBasicQueriesWS.class, features);
    }

}
