
package motion.database.ws.basicQueriesServiceWCF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IBasicQueriesWS", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBasicQueriesWS {


    /**
     * 
     * @param entityKind
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListAttributeGroupsDefinedResponse.ListAttributeGroupsDefinedResult
     * @throws IBasicQueriesWSListAttributeGroupsDefinedQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListAttributeGroupsDefined", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListAttributeGroupsDefined")
    @WebResult(name = "ListAttributeGroupsDefinedResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListAttributeGroupsDefined", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListAttributeGroupsDefined")
    @ResponseWrapper(localName = "ListAttributeGroupsDefinedResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListAttributeGroupsDefinedResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListAttributeGroupsDefinedResponse.ListAttributeGroupsDefinedResult listAttributeGroupsDefined(
        @WebParam(name = "entityKind", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String entityKind)
        throws IBasicQueriesWSListAttributeGroupsDefinedQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListSessionGroupsDefinedResponse.ListSessionGroupsDefinedResult
     * @throws IBasicQueriesWSListSessionGroupsDefinedQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListSessionGroupsDefined", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListSessionGroupsDefined")
    @WebResult(name = "ListSessionGroupsDefinedResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionGroupsDefined", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionGroupsDefined")
    @ResponseWrapper(localName = "ListSessionGroupsDefinedResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionGroupsDefinedResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListSessionGroupsDefinedResponse.ListSessionGroupsDefinedResult listSessionGroupsDefined()
        throws IBasicQueriesWSListSessionGroupsDefinedQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListMotionKindsDefinedResponse.ListMotionKindsDefinedResult
     * @throws IBasicQueriesWSListMotionKindsDefinedQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListMotionKindsDefined", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListMotionKindsDefined")
    @WebResult(name = "ListMotionKindsDefinedResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListMotionKindsDefined", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListMotionKindsDefined")
    @ResponseWrapper(localName = "ListMotionKindsDefinedResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListMotionKindsDefinedResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListMotionKindsDefinedResponse.ListMotionKindsDefinedResult listMotionKindsDefined()
        throws IBasicQueriesWSListMotionKindsDefinedQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param attributeName
     * @param entityKind
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListEnumValuesResponse.ListEnumValuesResult
     * @throws IBasicQueriesWSListEnumValuesQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListEnumValues", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListEnumValues")
    @WebResult(name = "ListEnumValuesResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListEnumValues", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListEnumValues")
    @ResponseWrapper(localName = "ListEnumValuesResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListEnumValuesResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListEnumValuesResponse.ListEnumValuesResult listEnumValues(
        @WebParam(name = "attributeName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String attributeName,
        @WebParam(name = "entityKind", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String entityKind)
        throws IBasicQueriesWSListEnumValuesQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param pageNo
     * @param pageSize
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListSessionContentsResponse.ListSessionContentsResult
     * @throws IBasicQueriesWSListSessionContentsQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListSessionContents", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListSessionContents")
    @WebResult(name = "ListSessionContentsResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionContents", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionContents")
    @ResponseWrapper(localName = "ListSessionContentsResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionContentsResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListSessionContentsResponse.ListSessionContentsResult listSessionContents(
        @WebParam(name = "pageSize", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int pageSize,
        @WebParam(name = "pageNo", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int pageNo)
        throws IBasicQueriesWSListSessionContentsQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sessionID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.GetSessionContentResponse.GetSessionContentResult
     * @throws IBasicQueriesWSGetSessionContentQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSessionContent", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetSessionContent")
    @WebResult(name = "GetSessionContentResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetSessionContent", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetSessionContent")
    @ResponseWrapper(localName = "GetSessionContentResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetSessionContentResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetSessionContentResponse.GetSessionContentResult getSessionContent(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionID)
        throws IBasicQueriesWSGetSessionContentQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param fileNames
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ValidateSessionFileSetResponse.ValidateSessionFileSetResult
     * @throws IBasicQueriesWSValidateSessionFileSetQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ValidateSessionFileSet", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ValidateSessionFileSet")
    @WebResult(name = "ValidateSessionFileSetResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ValidateSessionFileSet", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ValidateSessionFileSet")
    @ResponseWrapper(localName = "ValidateSessionFileSetResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ValidateSessionFileSetResponse")
    public motion.database.ws.basicQueriesServiceWCF.ValidateSessionFileSetResponse.ValidateSessionFileSetResult validateSessionFileSet(
        @WebParam(name = "fileNames", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        ArrayOfFileNameEntry fileNames)
        throws IBasicQueriesWSValidateSessionFileSetQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param entitiesToInclude
     * @param filter
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.GenericQueryXMLResponse.GenericQueryXMLResult
     * @throws IBasicQueriesWSGenericQueryXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GenericQueryXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GenericQueryXML")
    @WebResult(name = "GenericQueryXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GenericQueryXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GenericQueryXML")
    @ResponseWrapper(localName = "GenericQueryXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GenericQueryXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GenericQueryXMLResponse.GenericQueryXMLResult genericQueryXML(
        @WebParam(name = "filter", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        ArrayOfFilterPredicate filter,
        @WebParam(name = "entitiesToInclude", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        ArrayOfString entitiesToInclude)
        throws IBasicQueriesWSGenericQueryXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param entitiesToInclude
     * @param filter
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.GenericQueryUniformXMLResponse.GenericQueryUniformXMLResult
     * @throws IBasicQueriesWSGenericQueryUniformXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GenericQueryUniformXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GenericQueryUniformXML")
    @WebResult(name = "GenericQueryUniformXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GenericQueryUniformXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GenericQueryUniformXML")
    @ResponseWrapper(localName = "GenericQueryUniformXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GenericQueryUniformXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GenericQueryUniformXMLResponse.GenericQueryUniformXMLResult genericQueryUniformXML(
        @WebParam(name = "filter", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        ArrayOfFilterPredicate filter,
        @WebParam(name = "entitiesToInclude", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        ArrayOfString entitiesToInclude)
        throws IBasicQueriesWSGenericQueryUniformXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.GetPerformerByIdXMLResponse.GetPerformerByIdXMLResult
     * @throws IBasicQueriesWSGetPerformerByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetPerformerByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetPerformerByIdXML")
    @WebResult(name = "GetPerformerByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetPerformerByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetPerformerByIdXML")
    @ResponseWrapper(localName = "GetPerformerByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetPerformerByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetPerformerByIdXMLResponse.GetPerformerByIdXMLResult getPerformerByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetPerformerByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.GetSessionByIdXMLResponse.GetSessionByIdXMLResult
     * @throws IBasicQueriesWSGetSessionByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSessionByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetSessionByIdXML")
    @WebResult(name = "GetSessionByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetSessionByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetSessionByIdXML")
    @ResponseWrapper(localName = "GetSessionByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetSessionByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetSessionByIdXMLResponse.GetSessionByIdXMLResult getSessionByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetSessionByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     * @throws IBasicQueriesWSGetSessionLabelQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSessionLabel", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetSessionLabel")
    @WebResult(name = "GetSessionLabelResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetSessionLabel", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetSessionLabel")
    @ResponseWrapper(localName = "GetSessionLabelResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetSessionLabelResponse")
    public String getSessionLabel(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetSessionLabelQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.GetTrialByIdXMLResponse.GetTrialByIdXMLResult
     * @throws IBasicQueriesWSGetTrialByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetTrialByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetTrialByIdXML")
    @WebResult(name = "GetTrialByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetTrialByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetTrialByIdXML")
    @ResponseWrapper(localName = "GetTrialByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetTrialByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetTrialByIdXMLResponse.GetTrialByIdXMLResult getTrialByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetTrialByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.GetMeasurementByIdXMLResponse.GetMeasurementByIdXMLResult
     * @throws IBasicQueriesWSGetMeasurementByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetMeasurementByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetMeasurementByIdXML")
    @WebResult(name = "GetMeasurementByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetMeasurementByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetMeasurementByIdXML")
    @ResponseWrapper(localName = "GetMeasurementByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetMeasurementByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetMeasurementByIdXMLResponse.GetMeasurementByIdXMLResult getMeasurementByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetMeasurementByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.GetMeasurementConfigurationByIdXMLResponse.GetMeasurementConfigurationByIdXMLResult
     * @throws IBasicQueriesWSGetMeasurementConfigurationByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetMeasurementConfigurationByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetMeasurementConfigurationByIdXML")
    @WebResult(name = "GetMeasurementConfigurationByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetMeasurementConfigurationByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetMeasurementConfigurationByIdXML")
    @ResponseWrapper(localName = "GetMeasurementConfigurationByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetMeasurementConfigurationByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetMeasurementConfigurationByIdXMLResponse.GetMeasurementConfigurationByIdXMLResult getMeasurementConfigurationByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetMeasurementConfigurationByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.GetPerformerConfigurationByIdXMLResponse.GetPerformerConfigurationByIdXMLResult
     * @throws IBasicQueriesWSGetPerformerConfigurationByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetPerformerConfigurationByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetPerformerConfigurationByIdXML")
    @WebResult(name = "GetPerformerConfigurationByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetPerformerConfigurationByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetPerformerConfigurationByIdXML")
    @ResponseWrapper(localName = "GetPerformerConfigurationByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetPerformerConfigurationByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetPerformerConfigurationByIdXMLResponse.GetPerformerConfigurationByIdXMLResult getPerformerConfigurationByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetPerformerConfigurationByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.GetFileDataByIdXMLResponse.GetFileDataByIdXMLResult
     * @throws IBasicQueriesWSGetFileDataByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetFileDataByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetFileDataByIdXML")
    @WebResult(name = "GetFileDataByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetFileDataByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetFileDataByIdXML")
    @ResponseWrapper(localName = "GetFileDataByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.GetFileDataByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetFileDataByIdXMLResponse.GetFileDataByIdXMLResult getFileDataByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetFileDataByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListPerformersXMLResponse.ListPerformersXMLResult
     * @throws IBasicQueriesWSListPerformersXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListPerformersXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListPerformersXML")
    @WebResult(name = "ListPerformersXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformersXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListPerformersXML")
    @ResponseWrapper(localName = "ListPerformersXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListPerformersXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListPerformersXMLResponse.ListPerformersXMLResult listPerformersXML()
        throws IBasicQueriesWSListPerformersXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListPerformersWithAttributesXMLResponse.ListPerformersWithAttributesXMLResult
     * @throws IBasicQueriesWSListPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListPerformersWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListPerformersWithAttributesXML")
    @WebResult(name = "ListPerformersWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformersWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListPerformersWithAttributesXML")
    @ResponseWrapper(localName = "ListPerformersWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListPerformersWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListPerformersWithAttributesXMLResponse.ListPerformersWithAttributesXMLResult listPerformersWithAttributesXML()
        throws IBasicQueriesWSListPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sessionID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListSessionPerformersWithAttributesXMLResponse.ListSessionPerformersWithAttributesXMLResult
     * @throws IBasicQueriesWSListSessionPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListSessionPerformersWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListSessionPerformersWithAttributesXML")
    @WebResult(name = "ListSessionPerformersWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionPerformersWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionPerformersWithAttributesXML")
    @ResponseWrapper(localName = "ListSessionPerformersWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionPerformersWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListSessionPerformersWithAttributesXMLResponse.ListSessionPerformersWithAttributesXMLResult listSessionPerformersWithAttributesXML(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionID)
        throws IBasicQueriesWSListSessionPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param labID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListLabPerformersWithAttributesXMLResponse.ListLabPerformersWithAttributesXMLResult
     * @throws IBasicQueriesWSListLabPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListLabPerformersWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListLabPerformersWithAttributesXML")
    @WebResult(name = "ListLabPerformersWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListLabPerformersWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListLabPerformersWithAttributesXML")
    @ResponseWrapper(localName = "ListLabPerformersWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListLabPerformersWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListLabPerformersWithAttributesXMLResponse.ListLabPerformersWithAttributesXMLResult listLabPerformersWithAttributesXML(
        @WebParam(name = "labID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int labID)
        throws IBasicQueriesWSListLabPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param measurementID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListMeasurementPerformersWithAttributesXMLResponse.ListMeasurementPerformersWithAttributesXMLResult
     * @throws IBasicQueriesWSListMeasurementPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListMeasurementPerformersWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListMeasurementPerformersWithAttributesXML")
    @WebResult(name = "ListMeasurementPerformersWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListMeasurementPerformersWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListMeasurementPerformersWithAttributesXML")
    @ResponseWrapper(localName = "ListMeasurementPerformersWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListMeasurementPerformersWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListMeasurementPerformersWithAttributesXMLResponse.ListMeasurementPerformersWithAttributesXMLResult listMeasurementPerformersWithAttributesXML(
        @WebParam(name = "measurementID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int measurementID)
        throws IBasicQueriesWSListMeasurementPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param performerID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListPerformerSessionsXMLResponse.ListPerformerSessionsXMLResult
     * @throws IBasicQueriesWSListPerformerSessionsXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListPerformerSessionsXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListPerformerSessionsXML")
    @WebResult(name = "ListPerformerSessionsXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformerSessionsXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListPerformerSessionsXML")
    @ResponseWrapper(localName = "ListPerformerSessionsXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListPerformerSessionsXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListPerformerSessionsXMLResponse.ListPerformerSessionsXMLResult listPerformerSessionsXML(
        @WebParam(name = "performerID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int performerID)
        throws IBasicQueriesWSListPerformerSessionsXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sessionGroupID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListGroupSessionsWithAttributesXMLResponse.ListGroupSessionsWithAttributesXMLResult
     * @throws IBasicQueriesWSListGroupSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListGroupSessionsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListGroupSessionsWithAttributesXML")
    @WebResult(name = "ListGroupSessionsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListGroupSessionsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListGroupSessionsWithAttributesXML")
    @ResponseWrapper(localName = "ListGroupSessionsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListGroupSessionsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListGroupSessionsWithAttributesXMLResponse.ListGroupSessionsWithAttributesXMLResult listGroupSessionsWithAttributesXML(
        @WebParam(name = "sessionGroupID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionGroupID)
        throws IBasicQueriesWSListGroupSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param performerID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListPerformerSessionsWithAttributesXMLResponse.ListPerformerSessionsWithAttributesXMLResult
     * @throws IBasicQueriesWSListPerformerSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListPerformerSessionsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListPerformerSessionsWithAttributesXML")
    @WebResult(name = "ListPerformerSessionsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformerSessionsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListPerformerSessionsWithAttributesXML")
    @ResponseWrapper(localName = "ListPerformerSessionsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListPerformerSessionsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListPerformerSessionsWithAttributesXMLResponse.ListPerformerSessionsWithAttributesXMLResult listPerformerSessionsWithAttributesXML(
        @WebParam(name = "performerID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int performerID)
        throws IBasicQueriesWSListPerformerSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param labID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListLabSessionsWithAttributesXMLResponse.ListLabSessionsWithAttributesXMLResult
     * @throws IBasicQueriesWSListLabSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListLabSessionsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListLabSessionsWithAttributesXML")
    @WebResult(name = "ListLabSessionsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListLabSessionsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListLabSessionsWithAttributesXML")
    @ResponseWrapper(localName = "ListLabSessionsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListLabSessionsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListLabSessionsWithAttributesXMLResponse.ListLabSessionsWithAttributesXMLResult listLabSessionsWithAttributesXML(
        @WebParam(name = "labID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int labID)
        throws IBasicQueriesWSListLabSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param measurementConfID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfSessionsWithAttributesXMLResponse.ListMeasurementConfSessionsWithAttributesXMLResult
     * @throws IBasicQueriesWSListMeasurementConfSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListMeasurementConfSessionsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListMeasurementConfSessionsWithAttributesXML")
    @WebResult(name = "ListMeasurementConfSessionsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListMeasurementConfSessionsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfSessionsWithAttributesXML")
    @ResponseWrapper(localName = "ListMeasurementConfSessionsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfSessionsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfSessionsWithAttributesXMLResponse.ListMeasurementConfSessionsWithAttributesXMLResult listMeasurementConfSessionsWithAttributesXML(
        @WebParam(name = "measurementConfID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int measurementConfID)
        throws IBasicQueriesWSListMeasurementConfSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sessionID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListSessionSessionGroupsResponse.ListSessionSessionGroupsResult
     * @throws IBasicQueriesWSListSessionSessionGroupsQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListSessionSessionGroups", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListSessionSessionGroups")
    @WebResult(name = "ListSessionSessionGroupsResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionSessionGroups", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionSessionGroups")
    @ResponseWrapper(localName = "ListSessionSessionGroupsResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionSessionGroupsResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListSessionSessionGroupsResponse.ListSessionSessionGroupsResult listSessionSessionGroups(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionID)
        throws IBasicQueriesWSListSessionSessionGroupsQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sessionID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListSessionTrialsXMLResponse.ListSessionTrialsXMLResult
     * @throws IBasicQueriesWSListSessionTrialsXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListSessionTrialsXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListSessionTrialsXML")
    @WebResult(name = "ListSessionTrialsXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionTrialsXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionTrialsXML")
    @ResponseWrapper(localName = "ListSessionTrialsXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionTrialsXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListSessionTrialsXMLResponse.ListSessionTrialsXMLResult listSessionTrialsXML(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionID)
        throws IBasicQueriesWSListSessionTrialsXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sessionID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListSessionTrialsWithAttributesXMLResponse.ListSessionTrialsWithAttributesXMLResult
     * @throws IBasicQueriesWSListSessionTrialsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListSessionTrialsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListSessionTrialsWithAttributesXML")
    @WebResult(name = "ListSessionTrialsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionTrialsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionTrialsWithAttributesXML")
    @ResponseWrapper(localName = "ListSessionTrialsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionTrialsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListSessionTrialsWithAttributesXMLResponse.ListSessionTrialsWithAttributesXMLResult listSessionTrialsWithAttributesXML(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionID)
        throws IBasicQueriesWSListSessionTrialsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sessionID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListSessionPerformerConfsWithAttributesXMLResponse.ListSessionPerformerConfsWithAttributesXMLResult
     * @throws IBasicQueriesWSListSessionPerformerConfsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListSessionPerformerConfsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListSessionPerformerConfsWithAttributesXML")
    @WebResult(name = "ListSessionPerformerConfsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionPerformerConfsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionPerformerConfsWithAttributesXML")
    @ResponseWrapper(localName = "ListSessionPerformerConfsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListSessionPerformerConfsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListSessionPerformerConfsWithAttributesXMLResponse.ListSessionPerformerConfsWithAttributesXMLResult listSessionPerformerConfsWithAttributesXML(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionID)
        throws IBasicQueriesWSListSessionPerformerConfsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param trialID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListTrialMeasurementsWithAttributesXMLResponse.ListTrialMeasurementsWithAttributesXMLResult
     * @throws IBasicQueriesWSListTrialMeasurementsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListTrialMeasurementsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListTrialMeasurementsWithAttributesXML")
    @WebResult(name = "ListTrialMeasurementsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListTrialMeasurementsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListTrialMeasurementsWithAttributesXML")
    @ResponseWrapper(localName = "ListTrialMeasurementsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListTrialMeasurementsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListTrialMeasurementsWithAttributesXMLResponse.ListTrialMeasurementsWithAttributesXMLResult listTrialMeasurementsWithAttributesXML(
        @WebParam(name = "trialID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int trialID)
        throws IBasicQueriesWSListTrialMeasurementsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param measurementConfID
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfMeasurementsWithAttributesXMLResponse.ListMeasurementConfMeasurementsWithAttributesXMLResult
     * @throws IBasicQueriesWSListMeasurementConfMeasurementsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListMeasurementConfMeasurementsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListMeasurementConfMeasurementsWithAttributesXML")
    @WebResult(name = "ListMeasurementConfMeasurementsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListMeasurementConfMeasurementsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfMeasurementsWithAttributesXML")
    @ResponseWrapper(localName = "ListMeasurementConfMeasurementsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfMeasurementsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfMeasurementsWithAttributesXMLResponse.ListMeasurementConfMeasurementsWithAttributesXMLResult listMeasurementConfMeasurementsWithAttributesXML(
        @WebParam(name = "measurementConfID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int measurementConfID)
        throws IBasicQueriesWSListMeasurementConfMeasurementsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfigurationsWithAttributesXMLResponse.ListMeasurementConfigurationsWithAttributesXMLResult
     * @throws IBasicQueriesWSListMeasurementConfigurationsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListMeasurementConfigurationsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListMeasurementConfigurationsWithAttributesXML")
    @WebResult(name = "ListMeasurementConfigurationsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListMeasurementConfigurationsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfigurationsWithAttributesXML")
    @ResponseWrapper(localName = "ListMeasurementConfigurationsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfigurationsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListMeasurementConfigurationsWithAttributesXMLResponse.ListMeasurementConfigurationsWithAttributesXMLResult listMeasurementConfigurationsWithAttributesXML()
        throws IBasicQueriesWSListMeasurementConfigurationsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param subjectID
     * @param subjectType
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListFilesXMLResponse.ListFilesXMLResult
     * @throws IBasicQueriesWSListFilesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListFilesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListFilesXML")
    @WebResult(name = "ListFilesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListFilesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListFilesXML")
    @ResponseWrapper(localName = "ListFilesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListFilesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListFilesXMLResponse.ListFilesXMLResult listFilesXML(
        @WebParam(name = "subjectID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int subjectID,
        @WebParam(name = "subjectType", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String subjectType)
        throws IBasicQueriesWSListFilesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param subjectID
     * @param subjectType
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListFilesWithAttributesXMLResponse.ListFilesWithAttributesXMLResult
     * @throws IBasicQueriesWSListFilesWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListFilesWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListFilesWithAttributesXML")
    @WebResult(name = "ListFilesWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListFilesWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListFilesWithAttributesXML")
    @ResponseWrapper(localName = "ListFilesWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListFilesWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListFilesWithAttributesXMLResponse.ListFilesWithAttributesXMLResult listFilesWithAttributesXML(
        @WebParam(name = "subjectID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int subjectID,
        @WebParam(name = "subjectType", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String subjectType)
        throws IBasicQueriesWSListFilesWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param subjectID
     * @param subjectType
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListFileAttributeDataXMLResponse.ListFileAttributeDataXMLResult
     * @throws IBasicQueriesWSListFileAttributeDataXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListFileAttributeDataXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListFileAttributeDataXML")
    @WebResult(name = "ListFileAttributeDataXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListFileAttributeDataXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListFileAttributeDataXML")
    @ResponseWrapper(localName = "ListFileAttributeDataXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListFileAttributeDataXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListFileAttributeDataXMLResponse.ListFileAttributeDataXMLResult listFileAttributeDataXML(
        @WebParam(name = "subjectID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int subjectID,
        @WebParam(name = "subjectType", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String subjectType)
        throws IBasicQueriesWSListFileAttributeDataXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param subjectID
     * @param subjectEntity
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListFileAttributeDataWithAttributesXMLResponse.ListFileAttributeDataWithAttributesXMLResult
     * @throws IBasicQueriesWSListFileAttributeDataWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListFileAttributeDataWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListFileAttributeDataWithAttributesXML")
    @WebResult(name = "ListFileAttributeDataWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListFileAttributeDataWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListFileAttributeDataWithAttributesXML")
    @ResponseWrapper(localName = "ListFileAttributeDataWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListFileAttributeDataWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListFileAttributeDataWithAttributesXMLResponse.ListFileAttributeDataWithAttributesXMLResult listFileAttributeDataWithAttributesXML(
        @WebParam(name = "subjectID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int subjectID,
        @WebParam(name = "subjectEntity", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String subjectEntity)
        throws IBasicQueriesWSListFileAttributeDataWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param entityKind
     * @param attributeGroupName
     * @return
     *     returns motion.database.ws.basicQueriesServiceWCF.ListAttributesDefinedResponse.ListAttributesDefinedResult
     * @throws IBasicQueriesWSListAttributesDefinedQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListAttributesDefined", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListAttributesDefined")
    @WebResult(name = "ListAttributesDefinedResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListAttributesDefined", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListAttributesDefined")
    @ResponseWrapper(localName = "ListAttributesDefinedResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesServiceWCF.ListAttributesDefinedResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListAttributesDefinedResponse.ListAttributesDefinedResult listAttributesDefined(
        @WebParam(name = "attributeGroupName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String attributeGroupName,
        @WebParam(name = "entityKind", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String entityKind)
        throws IBasicQueriesWSListAttributesDefinedQueryExceptionFaultFaultMessage
    ;

}
