
package motion.database.ws.basicQueriesServiceWCF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IBasicQueriesWS", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBasicQueriesWS {


    /**
     * 
     * @param entitiesToInclude
     * @param filter
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.GenericQueryXMLResponse.GenericQueryXMLResult
     * @throws IBasicQueriesWSGenericQueryXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GenericQueryXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GenericQueryXML")
    @WebResult(name = "GenericQueryXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GenericQueryXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GenericQueryXML")
    @ResponseWrapper(localName = "GenericQueryXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GenericQueryXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GenericQueryXMLResponse.GenericQueryXMLResult genericQueryXML(
        @WebParam(name = "filter", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        ArrayOfFilterPredicate filter,
        @WebParam(name = "entitiesToInclude", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        ArrayOfString entitiesToInclude)
        throws IBasicQueriesWSGenericQueryXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param entitiesToInclude
     * @param filter
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.GenericQueryUniformXMLResponse.GenericQueryUniformXMLResult
     * @throws IBasicQueriesWSGenericQueryUniformXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GenericQueryUniformXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GenericQueryUniformXML")
    @WebResult(name = "GenericQueryUniformXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GenericQueryUniformXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GenericQueryUniformXML")
    @ResponseWrapper(localName = "GenericQueryUniformXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GenericQueryUniformXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GenericQueryUniformXMLResponse.GenericQueryUniformXMLResult genericQueryUniformXML(
        @WebParam(name = "filter", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        ArrayOfFilterPredicate filter,
        @WebParam(name = "entitiesToInclude", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        ArrayOfString entitiesToInclude)
        throws IBasicQueriesWSGenericQueryUniformXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.GetPerformerByIdXMLResponse.GetPerformerByIdXMLResult
     * @throws IBasicQueriesWSGetPerformerByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetPerformerByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetPerformerByIdXML")
    @WebResult(name = "GetPerformerByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetPerformerByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GetPerformerByIdXML")
    @ResponseWrapper(localName = "GetPerformerByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GetPerformerByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetPerformerByIdXMLResponse.GetPerformerByIdXMLResult getPerformerByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetPerformerByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.GetSessionByIdXMLResponse.GetSessionByIdXMLResult
     * @throws IBasicQueriesWSGetSessionByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSessionByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetSessionByIdXML")
    @WebResult(name = "GetSessionByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetSessionByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GetSessionByIdXML")
    @ResponseWrapper(localName = "GetSessionByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GetSessionByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetSessionByIdXMLResponse.GetSessionByIdXMLResult getSessionByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetSessionByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     * @throws IBasicQueriesWSGetSessionLabelQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSessionLabel", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetSessionLabel")
    @WebResult(name = "GetSessionLabelResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetSessionLabel", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GetSessionLabel")
    @ResponseWrapper(localName = "GetSessionLabelResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GetSessionLabelResponse")
    public String getSessionLabel(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetSessionLabelQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.GetTrialByIdXMLResponse.GetTrialByIdXMLResult
     * @throws IBasicQueriesWSGetTrialByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetTrialByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetTrialByIdXML")
    @WebResult(name = "GetTrialByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetTrialByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GetTrialByIdXML")
    @ResponseWrapper(localName = "GetTrialByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GetTrialByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetTrialByIdXMLResponse.GetTrialByIdXMLResult getTrialByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetTrialByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.GetSegmentByIdXMLResponse.GetSegmentByIdXMLResult
     * @throws IBasicQueriesWSGetSegmentByIdXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSegmentByIdXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/GetSegmentByIdXML")
    @WebResult(name = "GetSegmentByIdXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "GetSegmentByIdXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GetSegmentByIdXML")
    @ResponseWrapper(localName = "GetSegmentByIdXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.GetSegmentByIdXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.GetSegmentByIdXMLResponse.GetSegmentByIdXMLResult getSegmentByIdXML(
        @WebParam(name = "id", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int id)
        throws IBasicQueriesWSGetSegmentByIdXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListPerformersXMLResponse.ListPerformersXMLResult
     * @throws IBasicQueriesWSListPerformersXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListPerformersXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListPerformersXML")
    @WebResult(name = "ListPerformersXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformersXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListPerformersXML")
    @ResponseWrapper(localName = "ListPerformersXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListPerformersXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListPerformersXMLResponse.ListPerformersXMLResult listPerformersXML()
        throws IBasicQueriesWSListPerformersXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListPerformersWithAttributesXMLResponse.ListPerformersWithAttributesXMLResult
     * @throws IBasicQueriesWSListPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListPerformersWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListPerformersWithAttributesXML")
    @WebResult(name = "ListPerformersWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformersWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListPerformersWithAttributesXML")
    @ResponseWrapper(localName = "ListPerformersWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListPerformersWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListPerformersWithAttributesXMLResponse.ListPerformersWithAttributesXMLResult listPerformersWithAttributesXML()
        throws IBasicQueriesWSListPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param labID
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListLabPerformersWithAttributesXMLResponse.ListLabPerformersWithAttributesXMLResult
     * @throws IBasicQueriesWSListLabPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListLabPerformersWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListLabPerformersWithAttributesXML")
    @WebResult(name = "ListLabPerformersWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListLabPerformersWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListLabPerformersWithAttributesXML")
    @ResponseWrapper(localName = "ListLabPerformersWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListLabPerformersWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListLabPerformersWithAttributesXMLResponse.ListLabPerformersWithAttributesXMLResult listLabPerformersWithAttributesXML(
        @WebParam(name = "labID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int labID)
        throws IBasicQueriesWSListLabPerformersWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param performerID
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListPerformerSessionsXMLResponse.ListPerformerSessionsXMLResult
     * @throws IBasicQueriesWSListPerformerSessionsXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListPerformerSessionsXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListPerformerSessionsXML")
    @WebResult(name = "ListPerformerSessionsXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformerSessionsXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListPerformerSessionsXML")
    @ResponseWrapper(localName = "ListPerformerSessionsXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListPerformerSessionsXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListPerformerSessionsXMLResponse.ListPerformerSessionsXMLResult listPerformerSessionsXML(
        @WebParam(name = "performerID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int performerID)
        throws IBasicQueriesWSListPerformerSessionsXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param performerID
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListPerformerSessionsWithAttributesXMLResponse.ListPerformerSessionsWithAttributesXMLResult
     * @throws IBasicQueriesWSListPerformerSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListPerformerSessionsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListPerformerSessionsWithAttributesXML")
    @WebResult(name = "ListPerformerSessionsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformerSessionsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListPerformerSessionsWithAttributesXML")
    @ResponseWrapper(localName = "ListPerformerSessionsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListPerformerSessionsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListPerformerSessionsWithAttributesXMLResponse.ListPerformerSessionsWithAttributesXMLResult listPerformerSessionsWithAttributesXML(
        @WebParam(name = "performerID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int performerID)
        throws IBasicQueriesWSListPerformerSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param labID
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListLabSessionsWithAttributesXMLResponse.ListLabSessionsWithAttributesXMLResult
     * @throws IBasicQueriesWSListLabSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListLabSessionsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListLabSessionsWithAttributesXML")
    @WebResult(name = "ListLabSessionsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListLabSessionsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListLabSessionsWithAttributesXML")
    @ResponseWrapper(localName = "ListLabSessionsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListLabSessionsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListLabSessionsWithAttributesXMLResponse.ListLabSessionsWithAttributesXMLResult listLabSessionsWithAttributesXML(
        @WebParam(name = "labID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int labID)
        throws IBasicQueriesWSListLabSessionsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sessionID
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListSessionTrialsXMLResponse.ListSessionTrialsXMLResult
     * @throws IBasicQueriesWSListSessionTrialsXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListSessionTrialsXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListSessionTrialsXML")
    @WebResult(name = "ListSessionTrialsXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionTrialsXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListSessionTrialsXML")
    @ResponseWrapper(localName = "ListSessionTrialsXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListSessionTrialsXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListSessionTrialsXMLResponse.ListSessionTrialsXMLResult listSessionTrialsXML(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionID)
        throws IBasicQueriesWSListSessionTrialsXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sessionID
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListSessionTrialsWithAttributesXMLResponse.ListSessionTrialsWithAttributesXMLResult
     * @throws IBasicQueriesWSListSessionTrialsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListSessionTrialsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListSessionTrialsWithAttributesXML")
    @WebResult(name = "ListSessionTrialsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionTrialsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListSessionTrialsWithAttributesXML")
    @ResponseWrapper(localName = "ListSessionTrialsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListSessionTrialsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListSessionTrialsWithAttributesXMLResponse.ListSessionTrialsWithAttributesXMLResult listSessionTrialsWithAttributesXML(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionID)
        throws IBasicQueriesWSListSessionTrialsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param trialID
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListTrialSegmentsXMLResponse.ListTrialSegmentsXMLResult
     * @throws IBasicQueriesWSListTrialSegmentsXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListTrialSegmentsXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListTrialSegmentsXML")
    @WebResult(name = "ListTrialSegmentsXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListTrialSegmentsXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListTrialSegmentsXML")
    @ResponseWrapper(localName = "ListTrialSegmentsXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListTrialSegmentsXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListTrialSegmentsXMLResponse.ListTrialSegmentsXMLResult listTrialSegmentsXML(
        @WebParam(name = "trialID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int trialID)
        throws IBasicQueriesWSListTrialSegmentsXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param trialID
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListTrialSegmentsWithAttributesXMLResponse.ListTrialSegmentsWithAttributesXMLResult
     * @throws IBasicQueriesWSListTrialSegmentsWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListTrialSegmentsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListTrialSegmentsWithAttributesXML")
    @WebResult(name = "ListTrialSegmentsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListTrialSegmentsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListTrialSegmentsWithAttributesXML")
    @ResponseWrapper(localName = "ListTrialSegmentsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListTrialSegmentsWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListTrialSegmentsWithAttributesXMLResponse.ListTrialSegmentsWithAttributesXMLResult listTrialSegmentsWithAttributesXML(
        @WebParam(name = "trialID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int trialID)
        throws IBasicQueriesWSListTrialSegmentsWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param subjectID
     * @param subjectType
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListFilesXMLResponse.ListFilesXMLResult
     * @throws IBasicQueriesWSListFilesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListFilesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListFilesXML")
    @WebResult(name = "ListFilesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListFilesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListFilesXML")
    @ResponseWrapper(localName = "ListFilesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListFilesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListFilesXMLResponse.ListFilesXMLResult listFilesXML(
        @WebParam(name = "subjectID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int subjectID,
        @WebParam(name = "subjectType", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String subjectType)
        throws IBasicQueriesWSListFilesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param subjectID
     * @param subjectType
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListFilesWithAttributesXMLResponse.ListFilesWithAttributesXMLResult
     * @throws IBasicQueriesWSListFilesWithAttributesXMLQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListFilesWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListFilesWithAttributesXML")
    @WebResult(name = "ListFilesWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListFilesWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListFilesWithAttributesXML")
    @ResponseWrapper(localName = "ListFilesWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListFilesWithAttributesXMLResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListFilesWithAttributesXMLResponse.ListFilesWithAttributesXMLResult listFilesWithAttributesXML(
        @WebParam(name = "subjectID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int subjectID,
        @WebParam(name = "subjectType", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String subjectType)
        throws IBasicQueriesWSListFilesWithAttributesXMLQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param entityKind
     * @param attributeGroupName
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListAttributesDefinedResponse.ListAttributesDefinedResult
     * @throws IBasicQueriesWSListAttributesDefinedQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListAttributesDefined", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListAttributesDefined")
    @WebResult(name = "ListAttributesDefinedResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListAttributesDefined", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListAttributesDefined")
    @ResponseWrapper(localName = "ListAttributesDefinedResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListAttributesDefinedResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListAttributesDefinedResponse.ListAttributesDefinedResult listAttributesDefined(
        @WebParam(name = "attributeGroupName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String attributeGroupName,
        @WebParam(name = "entityKind", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String entityKind)
        throws IBasicQueriesWSListAttributesDefinedQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param entityKind
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListAttributeGroupsDefinedResponse.ListAttributeGroupsDefinedResult
     * @throws IBasicQueriesWSListAttributeGroupsDefinedQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListAttributeGroupsDefined", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListAttributeGroupsDefined")
    @WebResult(name = "ListAttributeGroupsDefinedResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListAttributeGroupsDefined", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListAttributeGroupsDefined")
    @ResponseWrapper(localName = "ListAttributeGroupsDefinedResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListAttributeGroupsDefinedResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListAttributeGroupsDefinedResponse.ListAttributeGroupsDefinedResult listAttributeGroupsDefined(
        @WebParam(name = "entityKind", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String entityKind)
        throws IBasicQueriesWSListAttributeGroupsDefinedQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListSessionGroupsDefinedResponse.ListSessionGroupsDefinedResult
     * @throws IBasicQueriesWSListSessionGroupsDefinedQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListSessionGroupsDefined", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListSessionGroupsDefined")
    @WebResult(name = "ListSessionGroupsDefinedResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionGroupsDefined", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListSessionGroupsDefined")
    @ResponseWrapper(localName = "ListSessionGroupsDefinedResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListSessionGroupsDefinedResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListSessionGroupsDefinedResponse.ListSessionGroupsDefinedResult listSessionGroupsDefined()
        throws IBasicQueriesWSListSessionGroupsDefinedQueryExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns motion.database.ws.BasicQueriesServiceWCF.ListMotionKindsDefinedResponse.ListMotionKindsDefinedResult
     * @throws IBasicQueriesWSListMotionKindsDefinedQueryExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ListMotionKindsDefined", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/IBasicQueriesWS/ListMotionKindsDefined")
    @WebResult(name = "ListMotionKindsDefinedResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListMotionKindsDefined", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListMotionKindsDefined")
    @ResponseWrapper(localName = "ListMotionKindsDefinedResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.BasicQueriesServiceWCF.ListMotionKindsDefinedResponse")
    public motion.database.ws.basicQueriesServiceWCF.ListMotionKindsDefinedResponse.ListMotionKindsDefinedResult listMotionKindsDefined()
        throws IBasicQueriesWSListMotionKindsDefinedQueryExceptionFaultFaultMessage
    ;

}
