
package motion.database.ws.basicQueriesService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import motion.database.ws.basicQueriesService.ListAttributesDefinedResponse.ListAttributesDefinedResult;
import motion.database.ws.basicQueriesService.ListPerformerSessionsWithAttributesXMLResponse.ListPerformerSessionsWithAttributesXMLResult;
import motion.database.ws.basicQueriesService.ListPerformerSessionsXMLResponse.ListPerformerSessionsXMLResult;
import motion.database.ws.basicQueriesService.ListSessionFilesXMLResponse.ListSessionFilesXMLResult;
import motion.database.ws.basicQueriesService.PerformQueryResponse.PerformQueryResult;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "BasicQueriesServiceSoap", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
public interface BasicQueriesServiceSoap {


    /**
     * 
     * @param performerID
     * @return
     *     returns motion.database.ws.basicQueriesService.ArrayOfSessionDetails
     */
    @WebMethod(operationName = "ListPerformerSessions", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/ListPerformerSessions")
    @WebResult(name = "ListPerformerSessionsResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformerSessions", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListPerformerSessions")
    @ResponseWrapper(localName = "ListPerformerSessionsResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListPerformerSessionsResponse")
    public ArrayOfSessionDetails listPerformerSessions(
        @WebParam(name = "performerID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int performerID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns motion.database.ws.basicQueriesService.ArrayOfFileDetails
     */
    @WebMethod(operationName = "ListSessionFiles", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/ListSessionFiles")
    @WebResult(name = "ListSessionFilesResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionFiles", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListSessionFiles")
    @ResponseWrapper(localName = "ListSessionFilesResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListSessionFilesResponse")
    public ArrayOfFileDetails listSessionFiles(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionID);

    /**
     * 
     * @param performerID
     * @return
     *     returns motion.database.ws.basicQueriesService.ListPerformerSessionsXMLResponse.ListPerformerSessionsXMLResult
     */
    @WebMethod(operationName = "ListPerformerSessionsXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/ListPerformerSessionsXML")
    @WebResult(name = "ListPerformerSessionsXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformerSessionsXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListPerformerSessionsXML")
    @ResponseWrapper(localName = "ListPerformerSessionsXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListPerformerSessionsXMLResponse")
    public ListPerformerSessionsXMLResult listPerformerSessionsXML(
        @WebParam(name = "performerID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int performerID);

    /**
     * 
     * @param performerID
     * @return
     *     returns motion.database.ws.basicQueriesService.ListPerformerSessionsWithAttributesXMLResponse.ListPerformerSessionsWithAttributesXMLResult
     */
    @WebMethod(operationName = "ListPerformerSessionsWithAttributesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/ListPerformerSessionsWithAttributesXML")
    @WebResult(name = "ListPerformerSessionsWithAttributesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListPerformerSessionsWithAttributesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListPerformerSessionsWithAttributesXML")
    @ResponseWrapper(localName = "ListPerformerSessionsWithAttributesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListPerformerSessionsWithAttributesXMLResponse")
    public ListPerformerSessionsWithAttributesXMLResult listPerformerSessionsWithAttributesXML(
        @WebParam(name = "performerID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int performerID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns motion.database.ws.basicQueriesService.ListSessionFilesXMLResponse.ListSessionFilesXMLResult
     */
    @WebMethod(operationName = "ListSessionFilesXML", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/ListSessionFilesXML")
    @WebResult(name = "ListSessionFilesXMLResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListSessionFilesXML", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListSessionFilesXML")
    @ResponseWrapper(localName = "ListSessionFilesXMLResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListSessionFilesXMLResponse")
    public ListSessionFilesXMLResult listSessionFilesXML(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        int sessionID);

    /**
     * 
     * @param query
     * @return
     *     returns motion.database.ws.basicQueriesService.PerformQueryResponse.PerformQueryResult
     */
    @WebMethod(operationName = "_PerformQuery", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/_PerformQuery")
    @WebResult(name = "_PerformQueryResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "_PerformQuery", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.PerformQuery")
    @ResponseWrapper(localName = "_PerformQueryResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.PerformQueryResponse")
    public PerformQueryResult performQuery(
        @WebParam(name = "query", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String query);

    /**
     * 
     * @param entityKind
     * @param attributeGroupName
     * @return
     *     returns motion.database.ws.basicQueriesService.ListAttributesDefinedResponse.ListAttributesDefinedResult
     */
    @WebMethod(operationName = "ListAttributesDefined", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService/ListAttributesDefined")
    @WebResult(name = "ListAttributesDefinedResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
    @RequestWrapper(localName = "ListAttributesDefined", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListAttributesDefined")
    @ResponseWrapper(localName = "ListAttributesDefinedResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService", className = "motion.database.ws.basicQueriesService.ListAttributesDefinedResponse")
    public ListAttributesDefinedResult listAttributesDefined(
        @WebParam(name = "attributeGroupName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String attributeGroupName,
        @WebParam(name = "entityKind", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicQueriesService")
        String entityKind);

}
