
package motion.database.ws.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "test_ws", targetNamespace = "http://tempuri.org", wsdlLocation = "C:\\DOCUME~1\\ADMINI~1\\USTAWI~1\\Temp\\tempdir1231359917564479536.tmp\\test-corrected_1.wsdl")
public class TestWs
    extends Service
{

    private final static URL TESTWS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file://wsdl/test-corrected.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TESTWS_WSDL_LOCATION = url;
    }

    public TestWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWs() {
        super(TESTWS_WSDL_LOCATION, new QName("http://tempuri.org", "test_ws"));
    }

    /**
     * 
     * @return
     *     returns TestWsSoap
     */
    @WebEndpoint(name = "test_ws")
    public TestWsSoap getTestWs() {
        return (TestWsSoap)super.getPort(new QName("http://tempuri.org", "test_ws"), TestWsSoap.class);
    }

}
