
package motion.database.ws.test;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "test_wsSoap", targetNamespace = "http://tempuri.org")
public interface TestWsSoap {


    /**
     * 
     * @return
     *     returns motion.database.ws.SqlResultStream
     */
    @WebMethod(operationName = "test_wm", action = "http://tempuri.orgtest_wm")
    @WebResult(name = "test_wmResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "test_wm", targetNamespace = "http://tempuri.org", className = "motion.database.ws.TestWm")
    @ResponseWrapper(localName = "test_wmResponse", targetNamespace = "http://tempuri.org", className = "motion.database.ws.TestWmResponse")
    public SqlResultStream testWm();

}
