
package motion.database.ws.fileStoremanService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "FileStoremanServiceSoap", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
public interface FileStoremanServiceSoap {


    /**
     * 
     * @param path
     * @param performerID
     */
    @WebMethod(operationName = "StorePerformerFiles", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService/StorePerformerFiles")
    @RequestWrapper(localName = "StorePerformerFiles", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.StorePerformerFiles")
    @ResponseWrapper(localName = "StorePerformerFilesResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.StorePerformerFilesResponse")
    public void storePerformerFiles(
        @WebParam(name = "performerID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        int performerID,
        @WebParam(name = "path", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String path);

    /**
     * 
     * @param sessionID
     * @param path
     */
    @WebMethod(operationName = "StoreSessionFiles", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService/StoreSessionFiles")
    @RequestWrapper(localName = "StoreSessionFiles", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.StoreSessionFiles")
    @ResponseWrapper(localName = "StoreSessionFilesResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.StoreSessionFilesResponse")
    public void storeSessionFiles(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        int sessionID,
        @WebParam(name = "path", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String path);

    /**
     * 
     * @param sessionId
     * @param description
     * @param path
     * @param filename
     * @return
     *     returns int
     */
    @WebMethod(operationName = "StoreSessionFile", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService/StoreSessionFile")
    @WebResult(name = "StoreSessionFileResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
    @RequestWrapper(localName = "StoreSessionFile", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.StoreSessionFile")
    @ResponseWrapper(localName = "StoreSessionFileResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.StoreSessionFileResponse")
    public int storeSessionFile(
        @WebParam(name = "sessionId", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        int sessionId,
        @WebParam(name = "path", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String path,
        @WebParam(name = "description", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String description,
        @WebParam(name = "filename", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String filename);

    /**
     * 
     * @param path
     * @param trialId
     */
    @WebMethod(operationName = "StoreTrialFiles", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService/StoreTrialFiles")
    @RequestWrapper(localName = "StoreTrialFiles", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.StoreTrialFiles")
    @ResponseWrapper(localName = "StoreTrialFilesResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.StoreTrialFilesResponse")
    public void storeTrialFiles(
        @WebParam(name = "trialId", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        int trialId,
        @WebParam(name = "path", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String path);

    /**
     * 
     * @param fileID
     */
    @WebMethod(operationName = "DownloadComplete", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService/DownloadComplete")
    @RequestWrapper(localName = "DownloadComplete", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.DownloadComplete")
    @ResponseWrapper(localName = "DownloadCompleteResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.DownloadCompleteResponse")
    public void downloadComplete(
        @WebParam(name = "fileID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        int fileID);

    /**
     * 
     * @param fileID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveFile", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService/RetrieveFile")
    @WebResult(name = "RetrieveFileResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
    @RequestWrapper(localName = "RetrieveFile", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.RetrieveFile")
    @ResponseWrapper(localName = "RetrieveFileResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.ws.fileStoremanService.RetrieveFileResponse")
    public String retrieveFile(
        @WebParam(name = "fileID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        int fileID);

}
