
package motion.database.ws.fileStoremanServiceWCF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IFileStoremanWS", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IFileStoremanWS {


    /**
     * 
     * @param measurementID
     * @param description
     * @param path
     * @param filename
     * @return
     *     returns int
     * @throws IFileStoremanWSStoreMeasurementResultFileFileAccessServiceExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "StoreMeasurementResultFile", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService/IFileStoremanWS/StoreMeasurementResultFile")
    @WebResult(name = "StoreMeasurementResultFileResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
    @RequestWrapper(localName = "StoreMeasurementResultFile", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.database.ws.fileStoremanServiceWCF.StoreMeasurementResultFile")
    @ResponseWrapper(localName = "StoreMeasurementResultFileResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.database.ws.fileStoremanServiceWCF.StoreMeasurementResultFileResponse")
    public int storeMeasurementResultFile(
        @WebParam(name = "measurementID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        int measurementID,
        @WebParam(name = "path", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String path,
        @WebParam(name = "description", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String description,
        @WebParam(name = "filename", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String filename)
        throws IFileStoremanWSStoreMeasurementResultFileFileAccessServiceExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param attributeName
     * @param resourceID
     * @param description
     * @param entity
     * @param path
     * @param filename
     * @return
     *     returns int
     * @throws IFileStoremanWSStoreAttributeFileFileAccessServiceExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "StoreAttributeFile", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService/IFileStoremanWS/StoreAttributeFile")
    @WebResult(name = "StoreAttributeFileResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
    @RequestWrapper(localName = "StoreAttributeFile", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.database.ws.fileStoremanServiceWCF.StoreAttributeFile")
    @ResponseWrapper(localName = "StoreAttributeFileResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.database.ws.fileStoremanServiceWCF.StoreAttributeFileResponse")
    public int storeAttributeFile(
        @WebParam(name = "resourceID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        int resourceID,
        @WebParam(name = "entity", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String entity,
        @WebParam(name = "attributeName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String attributeName,
        @WebParam(name = "path", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String path,
        @WebParam(name = "description", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String description,
        @WebParam(name = "filename", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String filename)
        throws IFileStoremanWSStoreAttributeFileFileAccessServiceExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param fileID
     * @param path
     * @throws IFileStoremanWSDownloadCompleteFileAccessServiceExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "DownloadComplete", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService/IFileStoremanWS/DownloadComplete")
    @RequestWrapper(localName = "DownloadComplete", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.database.ws.fileStoremanServiceWCF.DownloadComplete")
    @ResponseWrapper(localName = "DownloadCompleteResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.database.ws.fileStoremanServiceWCF.DownloadCompleteResponse")
    public void downloadComplete(
        @WebParam(name = "fileID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        int fileID,
        @WebParam(name = "path", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        String path)
        throws IFileStoremanWSDownloadCompleteFileAccessServiceExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param fileID
     * @return
     *     returns motion.database.ws.fileStoremanServiceWCF.FileData
     * @throws IFileStoremanWSRetrieveFileFileAccessServiceExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "RetrieveFile", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService/IFileStoremanWS/RetrieveFile")
    @WebResult(name = "RetrieveFileResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
    @RequestWrapper(localName = "RetrieveFile", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.database.ws.fileStoremanServiceWCF.RetrieveFile")
    @ResponseWrapper(localName = "RetrieveFileResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService", className = "motion.database.ws.fileStoremanServiceWCF.RetrieveFileResponse")
    public FileData retrieveFile(
        @WebParam(name = "fileID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/FileStoremanService")
        int fileID)
        throws IFileStoremanWSRetrieveFileFileAccessServiceExceptionFaultFaultMessage
    ;

}
