
package motion.database.ws.basicUpdatesServiceWCF;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BasicUpdatesWS", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", wsdlLocation = "http://83.230.112.43/Motion/BasicUpdatesWS.svc?wsdl")
public class BasicUpdatesWS
    extends Service
{

    private final static URL BASICUPDATESWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(motion.database.ws.basicUpdatesServiceWCF.BasicUpdatesWS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = motion.database.ws.basicUpdatesServiceWCF.BasicUpdatesWS.class.getResource(".");
            url = new URL(baseUrl, "http://83.230.112.43/Motion/BasicUpdatesWS.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://83.230.112.43/Motion/BasicUpdatesWS.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BASICUPDATESWS_WSDL_LOCATION = url;
    }

    public BasicUpdatesWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicUpdatesWS() {
        super(BASICUPDATESWS_WSDL_LOCATION, new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", "BasicUpdatesWS"));
    }

    /**
     * 
     * @return
     *     returns IBasicUpdatesWS
     */
    @WebEndpoint(name = "BasicHttpBinding_IBasicUpdatesWS")
    public IBasicUpdatesWS getBasicHttpBindingIBasicUpdatesWS() {
        return super.getPort(new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", "BasicHttpBinding_IBasicUpdatesWS"), IBasicUpdatesWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBasicUpdatesWS
     */
    @WebEndpoint(name = "BasicHttpBinding_IBasicUpdatesWS")
    public IBasicUpdatesWS getBasicHttpBindingIBasicUpdatesWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", "BasicHttpBinding_IBasicUpdatesWS"), IBasicUpdatesWS.class, features);
    }

}
