
package motion.database.ws.basicUpdatesServiceWCF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IBasicUpdatesWS", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBasicUpdatesWS {


    /**
     * 
     * @param performerData
     * @return
     *     returns int
     * @throws IBasicUpdatesWSCreatePerformerUpdateExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreatePerformer", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService/IBasicUpdatesWS/CreatePerformer")
    @WebResult(name = "CreatePerformerResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
    @RequestWrapper(localName = "CreatePerformer", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.CreatePerformer")
    @ResponseWrapper(localName = "CreatePerformerResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.CreatePerformerResponse")
    public int createPerformer(
        @WebParam(name = "performerData", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        PerformerData performerData)
        throws IBasicUpdatesWSCreatePerformerUpdateExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sessionDate
     * @param motionKindName
     * @param labID
     * @param sessionGroupIDs
     * @param sessionDescription
     * @param performerID
     * @return
     *     returns int
     * @throws IBasicUpdatesWSCreateSessionUpdateExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateSession", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService/IBasicUpdatesWS/CreateSession")
    @WebResult(name = "CreateSessionResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
    @RequestWrapper(localName = "CreateSession", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.CreateSession")
    @ResponseWrapper(localName = "CreateSessionResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.CreateSessionResponse")
    public int createSession(
        @WebParam(name = "labID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int labID,
        @WebParam(name = "motionKindName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String motionKindName,
        @WebParam(name = "performerID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int performerID,
        @WebParam(name = "sessionDate", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        XMLGregorianCalendar sessionDate,
        @WebParam(name = "sessionDescription", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String sessionDescription,
        @WebParam(name = "sessionGroupIDs", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        ArrayOfInt sessionGroupIDs)
        throws IBasicUpdatesWSCreateSessionUpdateExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param trialDescription
     * @param sessionID
     * @param trialDuration
     * @return
     *     returns int
     * @throws IBasicUpdatesWSCreateTrialUpdateExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateTrial", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService/IBasicUpdatesWS/CreateTrial")
    @WebResult(name = "CreateTrialResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
    @RequestWrapper(localName = "CreateTrial", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.CreateTrial")
    @ResponseWrapper(localName = "CreateTrialResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.CreateTrialResponse")
    public int createTrial(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int sessionID,
        @WebParam(name = "trialDescription", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String trialDescription,
        @WebParam(name = "trialDuration", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int trialDuration)
        throws IBasicUpdatesWSCreateTrialUpdateExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param startTime
     * @param segmentName
     * @param trialID
     * @param endTime
     * @return
     *     returns int
     * @throws IBasicUpdatesWSDefineTrialSegmentUpdateExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "DefineTrialSegment", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService/IBasicUpdatesWS/DefineTrialSegment")
    @WebResult(name = "DefineTrialSegmentResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
    @RequestWrapper(localName = "DefineTrialSegment", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.DefineTrialSegment")
    @ResponseWrapper(localName = "DefineTrialSegmentResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.DefineTrialSegmentResponse")
    public int defineTrialSegment(
        @WebParam(name = "trialID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int trialID,
        @WebParam(name = "segmentName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String segmentName,
        @WebParam(name = "startTime", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int startTime,
        @WebParam(name = "endTime", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int endTime)
        throws IBasicUpdatesWSDefineTrialSegmentUpdateExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param groupID
     * @param sessionID
     * @return
     *     returns boolean
     * @throws IBasicUpdatesWSAssignSessionToGroupUpdateExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "AssignSessionToGroup", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService/IBasicUpdatesWS/AssignSessionToGroup")
    @WebResult(name = "AssignSessionToGroupResult", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
    @RequestWrapper(localName = "AssignSessionToGroup", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.AssignSessionToGroup")
    @ResponseWrapper(localName = "AssignSessionToGroupResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.AssignSessionToGroupResponse")
    public boolean assignSessionToGroup(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int sessionID,
        @WebParam(name = "groupID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int groupID)
        throws IBasicUpdatesWSAssignSessionToGroupUpdateExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param update
     * @param attributeName
     * @param attributeValue
     * @param performerID
     * @throws IBasicUpdatesWSSetPerformerAttributeUpdateExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SetPerformerAttribute", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService/IBasicUpdatesWS/SetPerformerAttribute")
    @RequestWrapper(localName = "SetPerformerAttribute", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.SetPerformerAttribute")
    @ResponseWrapper(localName = "SetPerformerAttributeResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.SetPerformerAttributeResponse")
    public void setPerformerAttribute(
        @WebParam(name = "performerID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int performerID,
        @WebParam(name = "attributeName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String attributeName,
        @WebParam(name = "attributeValue", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String attributeValue,
        @WebParam(name = "update", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        boolean update)
        throws IBasicUpdatesWSSetPerformerAttributeUpdateExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param update
     * @param attributeName
     * @param sessionID
     * @param attributeValue
     * @throws IBasicUpdatesWSSetSessionAttributeUpdateExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SetSessionAttribute", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService/IBasicUpdatesWS/SetSessionAttribute")
    @RequestWrapper(localName = "SetSessionAttribute", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.SetSessionAttribute")
    @ResponseWrapper(localName = "SetSessionAttributeResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.SetSessionAttributeResponse")
    public void setSessionAttribute(
        @WebParam(name = "sessionID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int sessionID,
        @WebParam(name = "attributeName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String attributeName,
        @WebParam(name = "attributeValue", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String attributeValue,
        @WebParam(name = "update", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        boolean update)
        throws IBasicUpdatesWSSetSessionAttributeUpdateExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param update
     * @param attributeName
     * @param attributeValue
     * @param trialID
     * @throws IBasicUpdatesWSSetTrialAttributeUpdateExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SetTrialAttribute", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService/IBasicUpdatesWS/SetTrialAttribute")
    @RequestWrapper(localName = "SetTrialAttribute", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.SetTrialAttribute")
    @ResponseWrapper(localName = "SetTrialAttributeResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.SetTrialAttributeResponse")
    public void setTrialAttribute(
        @WebParam(name = "trialID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int trialID,
        @WebParam(name = "attributeName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String attributeName,
        @WebParam(name = "attributeValue", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String attributeValue,
        @WebParam(name = "update", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        boolean update)
        throws IBasicUpdatesWSSetTrialAttributeUpdateExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param update
     * @param attributeName
     * @param attributeValue
     * @param segmentID
     * @throws IBasicUpdatesWSSetSegmentAttributeUpdateExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SetSegmentAttribute", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService/IBasicUpdatesWS/SetSegmentAttribute")
    @RequestWrapper(localName = "SetSegmentAttribute", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.SetSegmentAttribute")
    @ResponseWrapper(localName = "SetSegmentAttributeResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.SetSegmentAttributeResponse")
    public void setSegmentAttribute(
        @WebParam(name = "segmentID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int segmentID,
        @WebParam(name = "attributeName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String attributeName,
        @WebParam(name = "attributeValue", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String attributeValue,
        @WebParam(name = "update", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        boolean update)
        throws IBasicUpdatesWSSetSegmentAttributeUpdateExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param update
     * @param attributeName
     * @param fileID
     * @param attributeValue
     * @throws IBasicUpdatesWSSetFileAttributeUpdateExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SetFileAttribute", action = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService/IBasicUpdatesWS/SetFileAttribute")
    @RequestWrapper(localName = "SetFileAttribute", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.SetFileAttribute")
    @ResponseWrapper(localName = "SetFileAttributeResponse", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService", className = "motion.database.ws.basicUpdatesServiceWCF.SetFileAttributeResponse")
    public void setFileAttribute(
        @WebParam(name = "fileID", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        int fileID,
        @WebParam(name = "attributeName", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String attributeName,
        @WebParam(name = "attributeValue", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        String attributeValue,
        @WebParam(name = "update", targetNamespace = "http://ruch.bytom.pjwstk.edu.pl/MotionDB/BasicUpdatesService")
        boolean update)
        throws IBasicUpdatesWSSetFileAttributeUpdateExceptionFaultFaultMessage
    ;

}
